# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sage < Formula
  desc "Docker Compose helper with sage.alias.* label shortcuts"
  homepage "https://github.com/jahnkelabs/sage"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.0.4/sage_1.0.4_Darwin_amd64.tar.gz"
      sha256 "6230c51c184a1dbe4acc0dd086ba32804cccf7c5332959fe05c85a1a3ce0861d"

      define_method(:install) do
        bin.install "sage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.0.4/sage_1.0.4_Darwin_arm64.tar.gz"
      sha256 "35c5060a18118a4777244fd46de3e6c765e8bf63998bf49f5a50c1cf2233d505"

      define_method(:install) do
        bin.install "sage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.0.4/sage_1.0.4_Linux_amd64.tar.gz"
      sha256 "b7afefe01aa22a178df5d44730d813bffe53fb0c27eeee5994d05d278489ecaa"
      define_method(:install) do
        bin.install "sage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.0.4/sage_1.0.4_Linux_arm64.tar.gz"
      sha256 "4561f8eeaf21950292aa15463d9b314f57e1063cbc8f43e7b66c9ab024b09651"
      define_method(:install) do
        bin.install "sage"
      end
    end
  end
end
