# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sage < Formula
  desc "Docker Compose helper with sage.alias.* label shortcuts"
  homepage "https://github.com/jahnkelabs/sage"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.2.0/sage_1.2.0_Darwin_amd64.tar.gz"
      sha256 "57499484fec4bb7ffd72877fb60a64f5098fe9e0869eb691e05980446b15c5dd"

      define_method(:install) do
        bin.install "sage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.2.0/sage_1.2.0_Darwin_arm64.tar.gz"
      sha256 "b1cdad2ef6a8e9798d107f09e08836d752b589580d6dcfa26795223610c1c0de"

      define_method(:install) do
        bin.install "sage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.2.0/sage_1.2.0_Linux_amd64.tar.gz"
      sha256 "4d056cd911c80e5110b41f8d2fbc584c84b6a18c9c35a58639e6c2a199966c26"
      define_method(:install) do
        bin.install "sage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jahnkelabs/sage/releases/download/v1.2.0/sage_1.2.0_Linux_arm64.tar.gz"
      sha256 "b99546cfd0e5d62fa3ac8b553caca488586c907f09fae790e54f94222fdbd775"
      define_method(:install) do
        bin.install "sage"
      end
    end
  end
end
